version = 1

exclude_patterns = [
    "*.lock",
    "*.toml",
    "*.yaml",
    "sanity_check/**",
    "backendeldery/tests/test_*.py",
]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"
enabled = true


