version = 1

[[analyzers]]
  name = "python"
  enabled = true

[[analyzers]]
  name = "test-coverage"
  enabled = true

# Optional: Specify the key used for reporting coverage data
  [analyzers.meta]
    key = "pytest"  # Or the key used in your 'deepsource report' command

