version = 1

test_patterns = ["**/tests/*"]

exclude_patterns = [
  "*.lock",
  "*.toml",
  "*.yaml",
  "sanity_check/**",
  "backendeldery/tests/*"
]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "test-coverage"