version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_HOST_PORT}:5432"  # Usa a variável DB_HOST_PORT para o mapeamento de porta
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: .
      dockerfile: backendeldery/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL_SYNC: ${DATABASE_URL_SYNC}
      DATABASE_URL_ASYNC: ${DATABASE_URL_ASYNC}
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
    volumes:
      - .:/app

volumes:
  postgres_data: