name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set environment variables
      env:
        DATABASE_URL: "sqlite:///./test.db"  # Use a valid SQLAlchemy URL
        MONGO_URI: "mock_mongo_uri"
        MONGO_DB: "mock_mongo_db"
      run: echo "Environment variables set"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry add --dev pytest pytest-cov deepsource
        poetry lock
        poetry install

    - name: Run DeepSource analysis
      uses: deepsource/deepsource-run@v2
      with:
        analyzer: python
        config: .deepsource.toml

    - name: Run tests
      env:
        DATABASE_URL: "sqlite:///./test.db"  # Use a valid SQLAlchemy URL
        MONGO_URI: "mock_mongo_uri"
        MONGO_DB: "mock_mongo_db"
      run: |
        poetry run pytest --junitxml=pytest-report.xml
        deepsource report --junit-file pytest-report.xml


