name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set environment variables
      env:
        DATABASE_URL: "sqlite:///./test.db"  # Use a valid SQLAlchemy URL
        MONGO_URI: "mock_mongo_uri"
        MONGO_DB: "mock_mongo_db"
      run: echo "Environment variables set"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry add --dev pytest pytest-cov pytest-json-report deepsource
        poetry lock
        poetry install

    - name: Run tests
      env:
        DATABASE_URL: "sqlite:///./test.db"  # Use a valid SQLAlchemy URL
        MONGO_URI: "mock_mongo_uri"
        MONGO_DB: "mock_mongo_db"
      run: |
        poetry run pytest --cov=backendeldery --cov-branch --cov-config=.coveragerc --json-report-file=report.json
    - name: Install DeepSource CLI
      run: |
        curl -fsSL https://deepsource.io/cli/latest | sh
        echo "$(pwd)/bin" >> $GITHUB_PATH  # Use environment files to add to PATH
        ls -l $(pwd)/bin  # List the contents of the bin directory
        echo $PATH  # Print the PATH environment variable

    - name: Verify DeepSource CLI installation
      run: |
        which deepsource  # Check if deepsource is in the PATH
        deepsource version  # Print the help message of deepsource

    - name: Upload coverage to DeepSource
      env:
        DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
      run: |
        deepsource report --test-report-file report.json